[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "surrealdb_recipe_demo_dataset"
version = "0.1.0"
dependencies = [
    "surrealdb",
    "torch",
]